### PR TITLE
Fixed #888 - Crash during 1.1 to 1.2 migration causes permanent loss …

### LINKED ISSUE #888: Crash during 1.1 to 1.2 migration causes permanent loss of data
If a user swipes out the app while 1.1 -> 1.2 migration is going on, then the following check in the code will cause data to be lost on the next run.

https://github.com/couchbase/couchbase-lite-java-core/blob/09b6111ace0d49c82e52d2749819f0158d013b7e/src/main/java/com/couchbase/lite/Manager.java#L831

### PR DESCRIPTION
**Pull request by hideki**
…of data

- Unit test for database upgrade from v1 to v2. Normal scenario and error scenario.

### CODE REVIEW

File: src/androidTest/java/com/couchbase/lite/ManagerTest.java [hunk 1]
```diff
@@ -13,6 +13,8 @@
  */
 package com.couchbase.lite;
 
+import android.provider.ContactsContract;
```
Comment (pasin) [inline src/androidTest/java/com/couchbase/lite/ManagerTest.java]: Do we require this?

File: src/androidTest/java/com/couchbase/lite/ManagerTest.java [hunk 2]
```diff
@@ -687,4 +689,96 @@ public void testGetUserAgent() {
         String userAgent = Manager.getUserAgent();
         assertTrue(userAgent.indexOf(Manager.PRODUCT_NAME + "/" + Version.SYNC_PROTOCOL_VERSION) != -1);
     }
+
+    /**
+     * Test Database upgrade from Schema v1 to v2, Normal scenario
+     */
+    public void testUpgradeDatabaseFrom110() throws Exception {
+        _testUpgradeDatabaseV1("ios110", "iosdb");
```
Comment (pasin) [inline src/androidTest/java/com/couchbase/lite/ManagerTest.java]: Maybe add to upgrade the android 110 db as well.

File: src/androidTest/java/com/couchbase/lite/ManagerTest.java [hunk 3]
```diff
@@ -687,4 +689,96 @@ public void testGetUserAgent() {
...
+        Manager mgr = new Manager(ctx, new ManagerOptions());
+        if (useForestDB)
+            mgr.setStorageType(Manager.FORESTDB_STORAGE);
+
+        // Open database
+        Database db = mgr.getExistingDatabase(dbname);
+        assertNotNull(db);
+        assertTrue(db.exists());
+        // validate upgrade db
+        validateDatabaseContentFromIOS(db);
```
Comment (pasin) [inline src/androidTest/java/com/couchbase/lite/ManagerTest.java]: Maybe also check if the old db files are removed correctly.

File: src/androidTest/java/com/couchbase/lite/ManagerTest.java [hunk 4]
```diff
@@ -687,4 +689,96 @@ public void testGetUserAgent() {
...
+        // close db & mgr
+        db.close();
+        mgr.close();
+    }
+
+    /**
+     * Test Database upgrade from Schema v1 to v2, With Fake temporary database upgrade file
+     */
+    public void testUpgradeDatabaseFrom110WithFakeTempDb() throws Exception {
+        _testUpgradeDatabaseV1WithFakeTempDb("ios110", "iosdb");
```
Comment (pasin) [inline src/androidTest/java/com/couchbase/lite/ManagerTest.java]: Maybe test android 110 db file as well.

File: src/androidTest/java/com/couchbase/lite/ManagerTest.java [hunk 5]
```diff
@@ -687,4 +689,96 @@ public void testGetUserAgent() {
...
+        if (useForestDB)
+            mgr.setStorageType(Manager.FORESTDB_STORAGE);
+
+        // Open database
+        Database db = mgr.getExistingDatabase(dbname);
+        assertNotNull(db);
+        assertTrue(db.exists());
+        // validate upgrade db
+        validateDatabaseContentFromIOS(db);
+
```
Comment (pasin) [inline src/androidTest/java/com/couchbase/lite/ManagerTest.java]: Maybe also check if the temp database is deleted correctly.
