### PR TITLE
Fixed #909 - Formalize User-Agent value

### LINKED ISSUE #909: Forest FC when save record (Note: ForestDB error code = -39)
Testing https://github.com/couchbase/couchbase-lite-android/issues/907#issuecomment-226263628 with latest forest
```
compile 'com.couchbase.lite:couchbase-lite-android:1.2.1'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:0.0.0-610'
```

Force close crash when save record:
```
06-16 08:39:12.414 21506-24360/com.myapp W/Sync: com.couchbase.lite.replicator.PullerInternal$9@4c06f45: failed to write {Record_bd4c1c18-9d00-40b9-beb5-3f30373c2230 #2-02a6efb5465c9aae8218835f57c41043 @54 DEL}: status=-1
06-16 08:39:12.414 21506-24360/com.myapp E/Sync: PullerInternal{unknown, pull, 9687a}: Progress: set error = org.apache.http.client.HttpResponseException
06-16 08:39:12.414 21506-25866/com.myapp E/Database: Error in getRevisionHistory() rev={Record_bb29c43e-a8ab-4f9e-b6ce-d1eda38ed297 #2-bf3438623171f857bd265281ebc11a70 @16991 DEL}
ForestException{domain=2, code=-39}
    at com.couchbase.cbforest.Document.init(Native Method)
    at com.couchbase.cbforest.Document.<init>(Document.java:87)
    at com.couchbase.cbforest.Database.getDocument(Database.java:36)
    at com.couchbase.lite.store.ForestDBStore.getRevisionHistory(ForestDBStore.java:386)
    at com.couchbase.lite.Database.getRevisionHistory(Database.java:1966)
    at com.couchbase.lite.Database.getRevisionHistoryDictStartingFromAnyAncestor(Database.java:1364)
    at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:391)
    at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:206)
    at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:223)
    at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:297)
    at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:218)
    at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:98)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
06-16 08:39:12.416 21506-25866/com.myapp E/RemoteRequest: RemoteRequestCompletionBlock throw Exception
     java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
         at com.couchbase.lite.Database.getRevisionHistoryDictStartingFromAnyAncestor(Database.java:1367)
         at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:391)
         at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:206)
         at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:223)
         at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:297)
         at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:218)
         at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:98)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
         at java.lang.Thread.run(Thread.java:761)
06-16 08:39:12.425 21506-24360/com.myapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 24360 (CBLManagerWorkE)

[ 06-16 08:39:12.426  1179: 1179 W/         ]
debuggerd: handling request: pid=21506 uid=10065 gid=10065 tid=24360
```

### PR DESCRIPTION
**Pull request by hideki**
- Implement getUserAgent() for Android platform.
- Added unit test for user agent.

Example: CouchbaseLite/1.2 (Android 4.4.4/armeabi-v7a 1.2.0/#000000)

### CODE REVIEW

File: src/androidTest/java/com/couchbase/lite/LiteTestCaseWithDB.java [hunk 1]
```diff
@@ -639,6 +641,14 @@ public void waitForPutCheckpointRequestWithSeq(MockDispatcher dispatcher, int se
         }
     }
 
+    protected void checkUserAgent(RecordedRequest request){
+        assertNotNull(request);
+        String userAgent = request.getHeader("User-Agent");
+        assertNotNull(userAgent);
+        assertTrue(userAgent.indexOf(Manager.PRODUCT_NAME + "/" + Version.SYNC_PROTOCOL_VERSION) != -1);
+        Log.e(TAG, "UserAgent: " + userAgent);
```
Comment (pasin) [inline src/androidTest/java/com/couchbase/lite/LiteTestCaseWithDB.java]: This is not an error. Can you change to Log.v?
