### PR TITLE
Fixed #1265 - 2.0: CouchbaseLiteException should be RuntimeException …

### LINKED ISSUE #1265: 2.0: CouchbaseLiteException should be RuntimeException or Exception
Currently CouchbaseLiteException extends from RuntimeException. However, some Exceptions could be thrown because of expected error like 409 - Conflict error. In some cases, CouchbaseLiteException is better to be extended from Exception.

Possible choices.
- Keep extending from RuntimeException
- Switch to extend from Exception.
- Define two CouchbaseLiteException(s) one is from RuntimeException, another one is from Exception.

### PR DESCRIPTION
**Pull request by hideki**
…or Exception

- Make CouchbaseLiteException extended from Exception instead of Runtime.
- Introduced CouchbaseLiteRuntimeException which could be thrown by inappropriate  codes
- API spec which has `thrown` keywords throws CouchbaseLiteException, others could throw CouchbaseLiteRuntimeException.

- In addition, removed /* package */ comment.
- some code formating.

### CODE REVIEW

File: shared/src/main/java/com/couchbase/lite/Database.java [hunk 1]
```diff
@@ -489,27 +487,26 @@ protected void finalize() throws Throwable {
...
+    Database copy() throws CouchbaseLiteException {
         return new Database(this.name, this.config);
     }
 
     //////// DATABASES:
 
     void mustBeOpen() {
         if (c4db == null)
-            throw new IllegalStateException("Database is not open.");
+            throw new CouchbaseLiteRuntimeException("Database is not open.");
```
Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/Database.java]: I think we should throw IllegalStateException instead of CouchbaseLiteRuntimeException as it's self described that this is in an inconsistent or illegal state that users shouldn't do. CouchbaseLiteRuntimeException should be something that LC might thrown but not expected?

File: shared/src/main/java/com/couchbase/lite/ReadOnlyDocument.java [hunk 2]
```diff
@@ -161,26 +164,23 @@ else if (c == '-')
...
 
-    /*package*/ ConflictResolver effectiveConflictResolver() {
+    ConflictResolver effectiveConflictResolver() {
         return getDatabase().getConflictResolver() != null ?
                 getDatabase().getConflictResolver() :
                 new DefaultConflictResolver();
     }
 
-    /* package */ boolean selectConflictingRevision() {
+    boolean selectConflictingRevision() throws CouchbaseLiteException {
```
Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/ReadOnlyDocument.java]: Is CouchbaseLiteException thrown from anything in this method? 
Or it should return void but throw CouchbaseLiteException instead?

File: shared/src/main/java/com/couchbase/lite/ReadOnlyDocument.java [hunk 3]
```diff
@@ -192,19 +192,20 @@ else if (c == '-')
         return true;
     }
 
-    /* package */ boolean selectCommonAncestor(ReadOnlyDocument doc1, ReadOnlyDocument doc2) {
+    boolean selectCommonAncestor(ReadOnlyDocument doc1, ReadOnlyDocument doc2)
+            throws CouchbaseLiteException {
```
Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/ReadOnlyDocument.java]: Is CouchbaseLiteException thrown from anything in this method? 
Or it should return void but throw CouchbaseLiteException instead?

**Comment by pasin** [comment]
As it has too many unrelated changes, I don't know if I can cover everything.

**Comment by pasin** [comment]
For further PR, PLEASE separate unrelated stuff such as code formatting into separated commits. It's really difficult to review.

**Comment by hideki** [comment]
@pasin, Sorry for including formatting changes in this PR.

**Comment by hideki** [comment]
@pasin Applied your feedbacks to this PR. please review changes?

https://github.com/couchbase/couchbase-lite-android/pull/1276/commits/df8bd973e8005e147f24e056884df6496c9f5b25
