### PR TITLE
 Fixed #1507 - 2.0: Request changes based on API Review

### LINKED ISSUE #1507: 2.0: Request changes based on API Review
## Request changes based on API review:

Database
* [x] Shouldn’t expose or implement C4Constants.
* [x] getActiveLiveQueries should not be public.
* [x] Change getDocument(documentID) to getDocument(id)
* [x] Change contains(documentID) to contains(id)
* [x] Change inBatch(Runnable action) to inBatch(runnable)
* [x] Change addDocumentChangeListener(docID, …) to addDocumentChangeListener(id, …)

Array (including MutableArray, ArrayInterface and MutableArrayInterface)
* [ ] encodeTo shouldn’t be public. (NOTE: Not avoidalble with current implementation. Write in javadoc)
* [ ] ~~FLEncodable shouldn’t be as public. (TODO: called from litecore.fleece.Encoder)~~
* [x] set/insert/addArray() should allow Array not just MutableArray
* [x] set/insert/addDictionary() should allow Dictionary not just MutableDictionary

Dictionary( including MutableDictionary, DictionaryInterface and MutableDictionaryInterface)
* [ ] encodeTo shouldn’t be public. (NOTE: Not avoidalble with current implementation. Write in javadoc)
* [ ] ~~FLEncodable shouldn’t be public. (TODO: called from litecore.fleece.Encoder)~~
MutableArray
* [x] set/insert/addArray() should allow Array not just MutableArray
* [x] set/insert/addDictionary() should allow Dictionary not just MutableDictionary

CBLConverter
* [x] Shouldn’t be public.

Query classes
* [x] Moved everything at root for consistency.

Replicator
* [x] networkReachable() shouldn’t be public. (TODO: NetworkReachabilityListener is interface)
* [x] networkUnreachable() shouldn’t be public. (TODO: NetworkReachabilityListener is interface)

ReplicatorConfiguration
* [x] ReplicatorConfigurator(Database, Object, ReplicatorType ….) should not be public.
* [x] copy() shouldn’t be public or should be removed if no use.

ArrayExpression
* [x] Expression.variable(name) should be moved to ArrayExpression.

Collation
* [x] For unicode collation, if the locale is not set, use the current device locale or default platform locale.
* [x] CollationExpression shouldn’t be public.

DataSource
* [x] Remove query()

Expression
* [x] asJson() shouldn’t be public.
* [ ] ~~Implement concat~~

Function
* [x] Change atan2(y, x) to atan2(x, y)

MetaExpression
* [x] Should extend Expression instead of PropertyExpression and include from(alias) method in it.

ValueIndex
* [x] Should be public

PropertyExpression
* [x] Need to move from internal to public.
* [x] PropertyExpression constructor shouldn’t be public.
* [x] Only from(alias) is public, the rest methods and kCBLAllPropertiesName are not.

Query
* [x] Missing addChangeListener(queue, listener).
* [x] getDatabase() shouldn’t be public.

QueryChange
* [x] Change getRows() to getResult()

ResultContext
* [x] Shouldn’t be public.

ResultSet
* [x] Make only next() and iterator() public. The rest shouldn’t be public.

SelectResult
* [x] from(alias) should return SelectResult.

NetworkReachabilityListener
* [x] Shouldn’t be public  (TODO: NetworkReachabilityListener is interface)

NetworkReachabilityManager
* [x] Shouldn’t be public

Log
* [x] Shouldn’t be public (TODO: two options - make package level, or move to internal)

## Request changes based on API Spec update

See: 
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/df94b46e0e5aa9e7eac2da006964553662cb76b2
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/ad7a29ae1872da9d41d4f1dfce71aeb28d26c7e3
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/4b501559f67f9e9f2e131ccbda85e65b244ab4d5

DatabaseConfiguration
* [x] getConflictResolver() returns the default one by default.
* [x] setConflictResolver(resolver) doesn’t allow to set null.
* [x] getDirectory() returns the default one by default.
* [x] setDirectory(directory) doesn’t allow to set null.
* [x] Use builder pattern.

Database
* [x] Remove contains(id: String) -> Bool as the redundant function with checking null from calling getDocument(id)
* [x] delete(document) : No-ops when the document doesn’t exists or has already been deleted in the database.
* [x] delete(document) : Throws not allow exception if deleting a newly created document.
* [x] purge(document): No-ops when the document doesn’t exists in the database.
* [x] purge(document):Throws not allow exception if purging a newly created document.

ReplicatorConfiguration
* [x] getConflictResolver() returns the default one by default.
* [x] setConflictResolver(resolver) doesn’t allow to set null.
* [x] New Endpoint interface, NetworkEndpoint class, and DatabaseEndpoint class.
* [x] Use builder pattern.

DocumentChange 
* [x] Add getDatabase().

Parameters
* [x] Add getValue().
* [x] Use builder pattern.

Expression
* [x] Add all() to express * (star). This can be used to express count(*) and select *.

FullTextExpression
* [x] Change index(indexName) to index(name).

Function
* [x] Remove all type check functions.

ResultSet
* [x] Add toList() (NOTE: Implement UnmodifilableList and return it)

### PR DESCRIPTION
**Pull request by hideki**
See github ticket for contents

Notes:
- first commit is for main change
- second commit is for unit tests
- `ResultSet.toList()` need to be updated after this.

### CODE REVIEW

File: shared/src/main/java/com/couchbase/lite/Database.java [hunk 1]
```diff
@@ -267,6 +258,19 @@ public void delete(Document document) throws CouchbaseLiteException {
...
+        if (document.isNewDocument())
+            throw new IllegalArgumentException("delete operation is not allowed with newly created document");
+
+        // not allowed to delete with old MutableDocument
+        if (document instanceof MutableDocument && ((MutableDocument) document).isSaved())
+            throw new IllegalArgumentException("a given document parameter is already saved or deleted. Not allowed to re-use it.");
+
+
+        // No-ops when the document does not exists or has already been deleted in the database.
+        if (!document.exists() || document.isDeleted())
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Database.java]: this is not correct. remove this.

File: shared/src/main/java/com/couchbase/lite/Database.java [hunk 2]
```diff
@@ -280,12 +284,15 @@ public void delete(Document document) throws CouchbaseLiteException {
     public void purge(Document document) throws CouchbaseLiteException {
         if (document == null)
             throw new IllegalArgumentException("a document parameter is null");
+        if (document.isNewDocument())
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Database.java]: check if revID is null

File: shared/src/main/java/com/couchbase/lite/Database.java [hunk 3]
```diff
@@ -280,12 +284,15 @@ public void delete(Document document) throws CouchbaseLiteException {
...
+            throw new IllegalArgumentException("purge operation is not allowed with newly created document");
 
         synchronized (lock) {
             prepareDocument(document);
 
+            // No-ops when the document doesn’t exists in the database.
             if (!document.exists())
-                throw new CouchbaseLiteException(Status.CBLErrorDomain, Status.NotFound);
+                return;
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Database.java]: Not necessary

File: shared/src/main/java/com/couchbase/lite/Database.java [hunk 4]
```diff
@@ -310,18 +317,18 @@ public void purge(Document document) throws CouchbaseLiteException {
      * like multiple inserts/updates; it saves the overhead of multiple database commits, greatly
      * improving performance.
      *
-     * @param action the action which is implementation of Runnable interface
+     * @param runnable the action which is implementation of Runnable interface
      * @throws CouchbaseLiteException Throws an exception if any error occurs during the operation.
      */
-    public void inBatch(Runnable action) throws CouchbaseLiteException {
+    public void inBatch(Runnable runnable) throws CouchbaseLiteException {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Database.java]: add null check for runnable

File: shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java [hunk 5]
```diff
@@ -0,0 +1,13 @@
+package com.couchbase.lite;
+
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java [hunk 6]
```diff
@@ -0,0 +1,13 @@
...
+public class DatabaseEndpoint implements Endpoint {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java]: final

File: shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java [hunk 7]
```diff
@@ -0,0 +1,13 @@
...
+    private Database database;
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java]: final

File: shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java [hunk 8]
```diff
@@ -0,0 +1,13 @@
...
+
+    public DatabaseEndpoint(final Database database) {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/DatabaseEndpoint.java]: - check null
- remove final

File: shared/src/main/java/com/couchbase/lite/Document.java [hunk 9]
```diff
@@ -501,7 +501,7 @@ FLSliceResult encode2() throws LiteCoreException {
         }
     }
 
-    protected FLDict getData() {
-        return _data;
+    boolean isNewDocument() {
+        return _c4doc == null;
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Document.java]: check by revID is null

File: shared/src/main/java/com/couchbase/lite/DocumentChange.java [hunk 10]
```diff
@@ -17,13 +17,20 @@
...
+
     private final String documentID;
 
-    DocumentChange(String documentID) {
+    DocumentChange(Database database, String documentID) {
+        this.database = database;
         this.documentID = documentID;
     }
 
+    public Database getDatabase() {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/DocumentChange.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Endpoint.java [hunk 11]
```diff
@@ -0,0 +1,4 @@
+package com.couchbase.lite;
+
+public interface Endpoint {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Endpoint.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Expression.java [hunk 12]
```diff
@@ -27,6 +23,11 @@
  * An expression used for constructing a query statement.
  */
 public abstract class Expression {
+
+    public static PropertyExpression all() {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Expression.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/FullTextExpression.java [hunk 13]
```diff
@@ -0,0 +1,26 @@
+package com.couchbase.lite;
+
+public final class FullTextExpression {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/FullTextExpression.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/FullTextExpression.java [hunk 14]
```diff
@@ -0,0 +1,26 @@
...
+    // Constructors
+    //---------------------------------------------
+    private FullTextExpression(String name) {
+        this.name = name;
+    }
+
+    //---------------------------------------------
+    // public level access
+    //---------------------------------------------
+    public static FullTextExpression index(String name) {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/FullTextExpression.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/FullTextExpression.java [hunk 15]
```diff
@@ -0,0 +1,26 @@
...
+        return new FullTextExpression(name);
+    }
+
+    public Expression match(String text) {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/FullTextExpression.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/FullTextIndex.java [hunk 16]
```diff
@@ -5,11 +5,11 @@
 import java.util.List;
 import java.util.Locale;
 
-public class FullTextIndex extends Index {
+public final class FullTextIndex extends Index {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/FullTextIndex.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/FullTextIndexItem.java [hunk 17]
```diff
@@ -1,6 +1,6 @@
 package com.couchbase.lite;
 
-public class FullTextIndexItem {
+public final class FullTextIndexItem {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/FullTextIndexItem.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Function.java [hunk 18]
```diff
@@ -1,10 +1,12 @@
 package com.couchbase.lite;
 
-import com.couchbase.lite.internal.query.expression.FunctionExpresson;
-
 import java.util.Arrays;
 
-public class Function {
+public final class Function {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Function.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/FunctionExpresson.java [hunk 19]
```diff
@@ -1,12 +1,10 @@
...
+package com.couchbase.lite;
 
 
-import com.couchbase.lite.Expression;
-
 import java.util.ArrayList;
 import java.util.List;
 
-public class FunctionExpresson extends Expression {
+class FunctionExpresson extends Expression {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/FunctionExpresson.java]: move to in Expression

File: shared/src/main/java/com/couchbase/lite/GroupBy.java [hunk 20]
```diff
@@ -4,7 +4,7 @@
 import java.util.Arrays;
 import java.util.List;
 
-public class GroupBy extends Query implements HavingRouter, OrderByRouter, LimitRouter {
+public final class GroupBy extends Query implements HavingRouter, OrderByRouter, LimitRouter {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/GroupBy.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Join.java [hunk 21]
```diff
@@ -16,7 +16,7 @@
 import java.util.HashMap;
 import java.util.Map;
 
-public abstract class Join {
+public class Join {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Join.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Join.java [hunk 22]
```diff
@@ -92,13 +96,17 @@ public static On innerJoin(DataSource datasource) {
         return new On(kCBLInnerJoin, datasource);
     }
 
-    public static On crossJoin(DataSource datasource) {
-        return new On(kCBLCrossJoin, datasource);
+    public static Join crossJoin(DataSource datasource) {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Join.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Joins.java [hunk 23]
```diff
@@ -5,7 +5,7 @@
 import java.util.Arrays;
 import java.util.List;
 
-public class Joins extends Query implements WhereRouter, OrderByRouter, LimitRouter {
+public final class Joins extends Query implements WhereRouter, OrderByRouter, LimitRouter {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Joins.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Meta.java [hunk 24]
```diff
@@ -1,17 +1,6 @@
 package com.couchbase.lite;
 
-import com.couchbase.lite.internal.query.expression.PropertyExpression;
-
 public class Meta {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Meta.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/MetaExpression.java [hunk 25]
```diff
@@ -0,0 +1,49 @@
+package com.couchbase.lite;
+
+import java.util.ArrayList;
+import java.util.List;
+
+public class MetaExpression extends Expression {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/MetaExpression.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/MetaExpression.java [hunk 26]
```diff
@@ -0,0 +1,49 @@
...
+    MetaExpression(String keyPath, String columnName, String from) {
+        this.keyPath = keyPath;
+        this.columnName = columnName;
+        this.from = from;
+    }
+
+    //---------------------------------------------
+    // public level access
+    //---------------------------------------------
+    public Expression from(String alias) {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/MetaExpression.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/MutableArray.java [hunk 27]
```diff
@@ -10,7 +10,7 @@
 /**
  * Array provides access to array data.
  */
-public class MutableArray extends Array implements MutableArrayInterface {
+public final class MutableArray extends Array implements MutableArrayInterface {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/MutableArray.java]: javadoc for all public methods

File: shared/src/main/java/com/couchbase/lite/MutableDictionary.java [hunk 28]
```diff
@@ -10,7 +10,7 @@
 /**
  * Dictionary provides access to dictionary data.
  */
-public class MutableDictionary extends Dictionary implements MutableDictionaryInterface {
+public final class MutableDictionary extends Dictionary implements MutableDictionaryInterface {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/MutableDictionary.java]: javadoc for all public methods

File: shared/src/main/java/com/couchbase/lite/Parameters.java [hunk 29]
```diff
@@ -1,78 +1,127 @@
...
+import com.couchbase.lite.internal.utils.JsonUtils;
 
 import org.json.JSONException;
 
 import java.util.Date;
 import java.util.HashMap;
 import java.util.Map;
 
-public class Parameters {
+public final class Parameters {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Parameters.java]: javadoc for all public class and methods

File: shared/src/main/java/com/couchbase/lite/PropertyExpression.java [hunk 30]
```diff
@@ -1,18 +1,16 @@
...
-
-import com.couchbase.lite.Expression;
+package com.couchbase.lite;
 
 import java.util.ArrayList;
 import java.util.List;
 
-public class PropertyExpression extends Expression {
-    public final static String kCBLAllPropertiesName = "";
+public final class PropertyExpression extends Expression {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/PropertyExpression.java]: javadoc for all public class and methods

File: shared/src/main/java/com/couchbase/lite/Query.java [hunk 31]
```diff
@@ -124,7 +122,9 @@ public Parameters getParameters() {
      * changes.
      */
     public void setParameters(Parameters parameters) {
-        this.parameters = parameters.copy();
+        if (parameters == null)
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Query.java]: Allow null for empty parameters

File: shared/src/main/java/com/couchbase/lite/Query.java [hunk 32]
```diff
@@ -84,7 +82,7 @@
     // Constructor
     //---------------------------------------------
     Query() {
-        parameters = new Parameters();
+        parameters = new Parameters.Builder().build();
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Query.java]: remove

File: shared/src/main/java/com/couchbase/lite/QueryChange.java [hunk 33]
```diff
@@ -28,8 +25,8 @@ public Query getQuery() {
         return query;
     }
 
-    public ResultSet getRows() {
-        return rows;
+    public ResultSet getResult() {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/QueryChange.java]: - getResults()
- javadoc

File: shared/src/main/java/com/couchbase/lite/ReplicatorChange.java [hunk 34]
```diff
@@ -1,6 +1,6 @@
 package com.couchbase.lite;
 
-public class ReplicatorChange {
+public final class ReplicatorChange {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ReplicatorChange.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/ReplicatorConfiguration.java [hunk 35]
```diff
@@ -14,7 +12,7 @@
 
 import static com.couchbase.lite.ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL;
 
-public class ReplicatorConfiguration {
+public final class ReplicatorConfiguration {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ReplicatorConfiguration.java]: javadoc for all public class and methods

File: shared/src/main/java/com/couchbase/lite/ReplicatorConfiguration.java [hunk 36]
```diff
@@ -53,79 +51,141 @@
...
+    private Map<String, String> headers = null;
     private byte[] pinnedServerCertificate = null;
     private List<String> channels = null;
     private List<String> documentIDs = null;
 
     //---------------------------------------------
-    // Constructors
+    // Builder
     //---------------------------------------------
+    public final static class Builder {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ReplicatorConfiguration.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/ReplicatorConfiguration.java [hunk 37]
```diff
@@ -53,79 +51,141 @@
...
+        //---------------------------------------------
+        // member variables
+        //---------------------------------------------
+        ReplicatorConfiguration conf;
+
+        //---------------------------------------------
+        // Constructors
+        //---------------------------------------------
+        public Builder(Database database, Endpoint target) {
+            conf = new ReplicatorConfiguration(database, target);
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ReplicatorConfiguration.java]: check null for database and target parameters

File: shared/src/main/java/com/couchbase/lite/SelectResult.java [hunk 38]
```diff
@@ -1,28 +1,26 @@
 package com.couchbase.lite;
 
 
-import com.couchbase.lite.internal.query.expression.PropertyExpression;
-
 public class SelectResult {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/SelectResult.java]: javadoc for all public class and methods

File: shared/src/main/java/com/couchbase/lite/SessionAuthenticator.java [hunk 39]
```diff
@@ -12,31 +9,28 @@
...
-    public SessionAuthenticator(String sessionID, Date expires, String cookieName) {
-        this.sessionID = sessionID;
-        this.expires = expires;
-        this.cookieName = cookieName;
+    public SessionAuthenticator(String sessionID) {
+        this(sessionID, DEFAULT_SYNC_GATEWAY_SESSION_ID_NAME);
     }
 
-    public SessionAuthenticator(String sessionID, String expires, String cookieName) {
+    public SessionAuthenticator(String sessionID, String cookieName) {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/SessionAuthenticator.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/URLEndpoint.java [hunk 40]
```diff
@@ -0,0 +1,53 @@
+package com.couchbase.lite;
+
+import java.net.URI;
+import java.net.URISyntaxException;
+
+import static com.couchbase.litecore.C4Replicator.kC4Replicator2Scheme;
+import static com.couchbase.litecore.C4Replicator.kC4Replicator2TLSScheme;
+
+public final class URLEndpoint implements Endpoint {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/URLEndpoint.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/URLEndpoint.java [hunk 41]
```diff
@@ -0,0 +1,53 @@
...
+    private String host = null;
+    private int port = -1;
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/URLEndpoint.java]: -1 might cause problem with litecore

File: shared/src/main/java/com/couchbase/lite/ValueIndex.java [hunk 42]
```diff
@@ -4,7 +4,7 @@
 import java.util.Arrays;
 import java.util.List;
 
-class ValueIndex extends Index {
+public final class ValueIndex extends Index {
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ValueIndex.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/ValueIndexItem.java [hunk 43]
```diff
@@ -1,10 +1,9 @@
 package com.couchbase.lite;
 
-
-public class ValueIndexItem {
+public final class ValueIndexItem {
     Expression expression;
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ValueIndexItem.java]: javadoc

File: shared/src/main/java/com/couchbase/lite/Database.java [hunk 44]
```diff
@@ -1116,6 +1133,8 @@ private Document save(Document document, boolean deletion) throws CouchbaseLiteE
 
                 // save succeeded
                 if (newDoc != null) {
+                    if (document instanceof MutableDocument)
+                        ((MutableDocument) document).markAsSaved();
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Database.java]: line 1167: add same check

ref: https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0-api-review/Objective-C/CBLDatabase.mm

File: shared/src/main/java/com/couchbase/lite/Database.java (hunk 2 above)
Comment (hideki) [reply shared/src/main/java/com/couchbase/lite/Database.java]: Actually checking if revID is null is same as checking if c4doc is null. To be consistent, Document.isNewDocument() checks if getRevID() is null.

**Comment by hideki** [comment]
NOTE: I am using thumbs-up icon to check item is completed.

**Comment by hideki** [comment]
TODO: Following check is not implemented in Java. 
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLDatabase.mm#L928-L941

**Comment by hideki** [comment]
TODOs:
- [ ] make sure that getter for boolean types such as deleted are in the form of isDeleted()

**Comment by hideki** [comment]
Another API updates

https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/17133caeb0b3a3d441f2e25d62e3d4d570261cad
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/ec1769fd07e6f3b3eee4b9662465828ae1b2d640
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/552500a7e50297eb504864842a6094a64332c16e


### ResultSet
- [ ] Change from ResultSet.toArray() to ResultSet.allResults().
- [ ] allResults() -> Array<Result> method will return the current unenumerated Result objects. After calling this method, all of the Result objects will be enumerated. Subsequence calls to next() method will return null. Subsequence calls to allResults() will return an empty array.
  - [ ] Why? The goal here is to make ResultSet API forward enumeration only at least for now. When LiteCore has done the optimization, we will revisit this again.
  - [ ] For iOS, this is the same behavior as the spec of the NSEnumerator’s -allObject method.
  - [ ] @Jim and @hideki. Please let me know if this works for .NET and Java regarding implementation and platform specific conflicts.

### Expression
- [ ] Remove concat() for 2.0. We should do this in 2.x.
- [ ] Fixed all() method to return PropertyExpression instead of FromExpression. Hence, remove FromExpression.
- [ ] Fixed ArrayExpression.any(variable), .every(variable), anyAndEvery(variable) to take VariableExpression instead of String name. Hence, Expression.variable(name) returns VariableExpression now.
- [ ] Please make sure to have isNOT(expression). I sent out an update about this before, but I have missed updating it in the spec.

### Type Safe Expression API
- [ ] We decided to make the Expression API type safe. 
  - [ ] For example, change Expression.multiply(Object) to Expression.multiply(Expression) or Function.count(Object) to Function.count(Expression).
- [ ] Add value expressions such as Expression.value(value), Expression.string(value), and so on.
  - [ ] We will not support Blob, Dictionary, and Array value type in 2.0. We could think about adding these based on demands later.
  - [ ] For the languages that support Literal Convertibles such as Swift, we could later add Literal Convertibles to automatically convert literal values to Expressions as well in 2.x.

### Database
- [ ] (Revised Behavior) delete(doc) :
  - [ ] Throws not-allow exception when deleting a newly created doc (no RevID).
  - [ ] No-ops when deleting a non existing document.
  - [ ] Go to conflict handler when delete an already deleted document. This will make it the same behavior as when pulling deleted documents. Also the default conflict resolver will handle this by returning theirs version which will be equal to no-ops.
- [ ] (Revised Behavior) purge(doc):
  - [ ] Throws not-allow exception when purging a newly created doc (no RevID).
  - [ ] No-ops when purging a non existing document. For implementation, I understand LC has already make the operation no-ops.

**Comment by hideki** [comment]
Todo:
- [ ] Review all javadocs
