### PR TITLE
2.0 API updates and bug fixes

### LINKED ISSUE #1174: 2.0: API update
- [x] Add Database.count and Database.contain(id)
- [x] Add ReadOnlyDictionary.keys
- [x]  Add Query.explain() and Query.profile()
- [x] Add some comment specific to Android platform on DatabaseConfiguration and Database constructor.

Please see https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/9a4222109366e192863dd02005cb58e158352183

### PR DESCRIPTION
**Pull request by hideki**
#1174 - 2.0: API update
  - Implemented DatabaseConfiguration(Context) for Android
  - Implemented Dictionary.getKeys() instead of getAllKeys()
  - Removed Database(String) consturctor which is inrelebant for Android.
  - Implemented Query.explain()
  - Ported two Unit Test cses for Document Change Listener
  - Ported testRemoveDictionary() unit test. And also fixed the bug which was found by the test

#1158 - 2.0: getLong/setLong does not work as expected
  - Casting to int from long cause data loss. Fixed this.

#1160 - 2.0: Double/Float without decimal are returned as Integer
  - Fleece stores double or float value without decimal fraction as the integer value. Fixed the test cases

#1161 - 2.0: Double value which is stored in fleece is returned as Float.
  - Fleece stores the double value, which is same as the float value, as the float value. Fixed the test cases

#1170 - Array and Dictionary should throw ConcurrentModificationException if Array or Dictionary is modified.
 - Check Array/Dictionary updates during iteration.

Note: For details, please refer each commit?

### CODE REVIEW

File: shared/src/main/java/com/couchbase/lite/ReadOnlyDictionary.java [hunk 1]
```diff
@@ -99,7 +104,7 @@ public Number getNumber(String key) {
     @Override
     public int getInt(String key) {
         FLValue value = fleeceValue(key);
-        return value != null ? value.asInt() : 0;
+        return value != null ? (int)value.asInt() : 0;
```
Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/ReadOnlyDictionary.java]: Same here. It seems like asInt() doesn't return int?

File: android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
+package com.couchbase.lite;
+
+import android.content.Context;
+
+public class DatabaseConfiguration extends BaseDatabaseConfiguration{
```
Comment (pasin) [inline android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java]: Formatting :)

File: shared/src/main/java/com/couchbase/lite/Dictionary.java [hunk 3]
```diff
@@ -356,7 +366,7 @@ public Date getDate(String key) {
      */
     @Override
     public Map<String, Object> toMap() {
-        Map<String, Object> result = map != null ? new HashMap<>(map) : new HashMap<String, Object>();
+        Map<String, Object> result = map != null ? new TreeMap<>(map) : new TreeMap<String, Object>();
```
Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/Dictionary.java]: FYI, JSONObject is also used HashMap as a backing data.

https://android.googlesource.com/platform/dalvik/+/f2f7880a40aed1c8d9c27db49226e47396556aac/libcore/json/src/main/java/org/json/JSONObject.java

File: android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java [hunk 4]
```diff
@@ -701,9 +700,10 @@ public void testSetGetFloatNumbers() {
         save(doc, "array", array, new Validator<Array>() {
             @Override
             public void validate(Array a) {
-                // TODO: https://github.com/couchbase/couchbase-lite-android/issues/1160
-//                assertEquals(1.00, a.getObject(0));
-//                assertEquals(1.00, a.getNumber(0));
+                // NOTE: Number which has no floating part is stored as Integer.
+                //       This causes type difference between before and after storing data into the database.
+                assertEquals(1.00, ((Number)a.getObject(0)).doubleValue(), 0.0);
```
Comment (hideki) [inline android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java]: LiteCore (Fleece) stores 1.0 as 1 to save space.
```c
 void Encoder::writeDouble(double n) {
        throwIf(std::isnan(n), InvalidData, "Can't write NaN");
        if (n == (int64_t)n) {
            return writeInt((int64_t)n);
        } else if (n == (float)n) {
            return _writeFloat((float)n);
        } else {
            littleEndianDouble swapped = n;
            uint8_t buf[2 + sizeof(swapped)];
            buf[0] = 0x08; // 'double' size flag
            buf[1] = 0;
            memcpy(&buf[2], &swapped, sizeof(swapped));
            writeValue(kFloatTag, buf, sizeof(buf));
        }
    }
```

File: android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java [hunk 5]
```diff
@@ -156,16 +156,16 @@ public void validate(Array a) {
...
+                assertEquals(1, ((Number)a.getObject(4)).intValue());
+                assertEquals(-1, ((Number)a.getObject(5)).intValue());
                 assertEquals(1.1, a.getObject(6));
                 assertEquals(kArrayTestDate, a.getObject(7));
                 assertEquals(null, a.getObject(8));
 
                 // dictionary
                 Dictionary subdict = (Dictionary) a.getObject(9);
-                Map<String, Object> expectedMap = new HashMap<>();
+                Map<String, Object> expectedMap = new TreeMap<>();
```
Comment (hideki) [inline android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java]: TreeMap is easier for testing as the order of keys is guaranteed.
I can switch it back.

File: android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java [hunk 6]
```diff
@@ -716,9 +716,8 @@ public void validate(Array a) {
                 assertEquals(1.49F, a.getFloat(1), 0.0F);
                 assertEquals(1.49, a.getDouble(1), 0.0);
 
-                // TODO:
-//                assertEquals(1.50, a.getObject(2));
-//                assertEquals(1.50, a.getNumber(2));
+                assertEquals(1.50, ((Number)a.getObject(2)).doubleValue(), 0.0);
+                assertEquals(1.50, a.getNumber(2).doubleValue(), 0.0);
```
Comment (hideki) [inline android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java]: same reason with above. Some of the Double value is stored as Float.
1.50 on java is Double, and a.getObject() returns Float as Fleece store it as Float.

File: android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DictionaryTest.java [hunk 7]
```diff
@@ -3,34 +3,35 @@
...
+import static org.junit.Assert.assertNull;
 import static org.junit.Assert.assertTrue;
 
 public class DictionaryTest extends BaseTest {
     @Test
     public void testCreateDictionary() {
         Dictionary address = new Dictionary();
         assertEquals(0, address.count());
-        assertEquals(new HashMap<String, Object>(), address.toMap());
+        assertEquals(new TreeMap<String, Object>(), address.toMap());
```
Comment (hideki) [inline android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DictionaryTest.java]: I will switch it back to HashMap. And will consider another solution for map comparison.

File: android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java (hunk 6 above)
Comment (pasin) [inline android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java]: What is the rule to store as float or double?

File: android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DocumentTest.java [hunk 8]
```diff
@@ -177,16 +177,16 @@ public void testCreateDocWithDict() {
         assertTrue(doc1b.exists());
         assertFalse(doc1b.isDeleted());
         assertEquals(doc1a.getId(), doc1b.getId());
-        assertEquals(dict, doc1b.toMap());
+        assertEquals(dict.toString(), doc1b.toMap().toString());
```
Comment (hideki) [inline android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/DocumentTest.java]: I will take a look Hamcrest's assertion

File: android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java (hunk 2 above)
Comment (hideki) [inline android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java]: ok

File: android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+    private Context context;
+
+    public DatabaseConfiguration() {
```
Comment (hideki) [inline android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java]: `Database(String name)` is not allowed for Android. But `DatabaseConfiguration()` should be allowed because the user can set directory.

File: shared/src/main/java/com/couchbase/lite/Dictionary.java [hunk 10]
```diff
@@ -97,6 +99,14 @@ public Dictionary set(Map<String, Object> dictionary) {
         return this;
     }
 
+    @Override
+    public List<String> getKeys() {
+        if (!changed)
+            return super.getKeys();
+        else
+            return allKeys();
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Dictionary.java]: Both Dictionary.allKeys() and ReadOnlyDictonary.getKeys() create new instance of `List<String>`. It is not necessary.

File: shared/src/main/java/com/couchbase/lite/ReadOnlyDictionary.java (hunk 1 above)
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ReadOnlyDictionary.java]: Fleece has one type for integral numbers. It is Integer. 
Fleece's Integer is equivalent with Java Long. 2^64.

File: shared/src/main/java/com/couchbase/lite/ReadOnlyArray.java [hunk 11]
```diff
@@ -88,7 +88,7 @@ public Number getNumber(int index) {
      */
     @Override
     public int getInt(int index) {
-        return fleeceValue(index).asInt();
+        return (int)fleeceValue(index).asInt();
```
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/ReadOnlyArray.java]: Fleece Integer is equivalent with Java Long.
I implemented JNI to return long. Otherwise, Java could not support Long.MAX and Long.MIN.

File: shared/src/main/java/com/couchbase/lite/Dictionary.java (hunk 10 above)
Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/Dictionary.java]: Could you double check allKeys() method of the Dictionary? I remembered that it does cache the keys.

File: shared/src/main/java/com/couchbase/lite/Dictionary.java (hunk 3 above)
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Dictionary.java]: As TreeMap maintains the order of keys, I changed it to TreeMap instead of HashMap. I will switch back to HashMap.

File: android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java (hunk 9 above)
Comment (pasin) [inline android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java]: I think we just don't allow. Otherwise we will need to check whether users set directory or not and throw runtime exception. In the future, if this becomes a concern of difficult to use, we can add back. What do you think?

**Comment by hideki** [comment]
TODOs:
- Switch back TreeMap to HashMap
- Fix Map value comparison for unit test

**Comment by hideki** [comment]
@pasin Can you review this PR again? Thanks!

**Comment by pasin** [comment]
I have added my comment about copying keys and DatabaseConfiguration constructor. Can you review?

File: android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java (hunk 9 above)
Comment (pasin) [inline android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java]: Can you review my comment above^?

File: android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java (hunk 6 above)
Comment (hideki) [inline android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/ArrayTest.java]: Depend on following logic
```c
void Encoder::writeDouble(double n) {
        throwIf(std::isnan(n), InvalidData, "Can't write NaN");
        if (n == (int64_t)n) {
            return writeInt((int64_t)n);
        } else if (n == (float)n) {
            return _writeFloat((float)n);
        } else {
            littleEndianDouble swapped = n;
            uint8_t buf[2 + sizeof(swapped)];
            buf[0] = 0x08; // 'double' size flag
            buf[1] = 0;
            memcpy(&buf[2], &swapped, sizeof(swapped));
            writeValue(kFloatTag, buf, sizeof(buf));
        }
    }
```

File: shared/src/main/java/com/couchbase/lite/Dictionary.java (hunk 10 above)
Comment (hideki) [inline shared/src/main/java/com/couchbase/lite/Dictionary.java]: I will check

Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/Dictionary.java]: Can you review my comment above ^?

**Comment by hideki** [comment]
I did not read your latest comment. I will check Dictionary keys.

File: android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java (hunk 9 above)
Comment (hideki) [inline android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java]: So you are saying `DatabaseConfiguration` constructor only support `DatabaseConfiguration(Context)` for Android? To simplify the API, this could be a reasonable solution.

Comment (pasin) [inline android/CouchbaseLite/src/main/java/com/couchbase/lite/DatabaseConfiguration.java]: Yes.

**Comment by hideki** [comment]
As you said, keys variable is cached.

**Comment by hideki** [comment]
@pasin Could you please re-review PR? Thanks!

**Comment by hideki** [comment]
Made a new ticket for `Hamcrest matchers` for unit tests
https://github.com/couchbase/couchbase-lite-android/issues/1181

File: shared/src/main/java/com/couchbase/lite/Dictionary.java [hunk 12]
```diff
@@ -103,9 +103,9 @@ public Dictionary set(Map<String, Object> dictionary) {
     @Override
     public List<String> getKeys() {
         if (!changed)
-            return super.getKeys();
+            return new ArrayList(super.getKeys());
```
Comment (pasin) [inline shared/src/main/java/com/couchbase/lite/Dictionary.java]: There is no needs to create a new ArrayList here as super.getKeys() already returns a copy.

**Comment by hideki** [comment]
@pasin Thank you for catching the problem.
